name: Stacks (What-If Validation)

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  validation:
    name: "What-If Validation"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: What-If
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: whatIf
          name: Development-WhatIf
          location: canadacentral
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: ./summit/main.bicep
          parameters-file: ./summit/main.bicepparam
